# Generated by Django 3.1.5 on 2021-03-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_remove_time_day'),
        ('students', '0003_auto_20210311_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentschedule',
            name='day',
        ),
        migrations.AddField(
            model_name='studentschedule',
            name='day',
            field=models.ManyToManyField(to='teachers.Day'),
        ),
    ]
