# Generated by Django 3.1.5 on 2021-03-11 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20210311_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='day',
        ),
    ]
